### ISSUE TITLE
Restructure Project With React Boilerplate

### ISSUE THREAD

**Issue by rowlandekemezie** [FBDevCLagos/hiddenwisdom-react-js#2]
To help us get up to speed and not to have problem scaling the app in the coming days, I suggest:

1) we use [React boilerplate](https://github.com/mxstbr/react-boilerplate)
2) we setup project structure to help anybody coming onboard to follow the pattern
3) I can handle it and integrate with the existing app when approved.

Let's make suggestions on this and concerns.

**Comment by innocentamadi** [comment]
Rowland!! I was wondering how long it would take you!
Do you foresee problems in future with the current setup? I think React Boilerplate looks cool too. 
With you handling that, I'm fine with it. Totally. 
Depends on @andela-abankole though. Take it up with him ?

**Comment by akinjide** [comment]
@andela-rekemezie But do you know the problem with boilerplate especially if it has contributions?

**Comment by rowlandekemezie** [comment]
Everything comes with its own problem. But I don't know the exact problem you're talking about. 
There might be nothing wrong with the current structure especially the one @andela-eakinyele is working on. Sorry, I didn't also check the name of the branch before submitting this issue. That said, 

1) react-boilerplate has almost 9000 stars already.
2) we can version control it. That's, updates to it doesn't affect us. 
3) the current structure doesn't take into account Redux and ImmutableJs for state management.
4) as an open source project, I think we need to use what the industry certify and learn in that line.

See [project](https://github.com/andela-rekemezie/media-library) built with  [create-react-app](https://github.com/andela-rekemezie/media-library). I didn't configure anything.

I'm generally open to whatever we conclude on. And we can make the decision fast.

**Comment by emmyakin** [comment]
The boiler plate has a lot of abstractions, might need a lot of trimming for things we don't need.
We hadn't exactly decided to use redux, so the setup wasn't tailored to that.
And then, we were hoping folks could learn react steadily instead of having to decipher the codebase.
@andela-rekemezie  But then, all you need do as of now is add the redux parts and refactor some, so go for it
Create a feature branch I think

**Comment by rowlandekemezie** [comment]
Thanks, @andela-eakinyele, it looks like there are plenty abstractions but React is all about abstraction, hence it's declarative paradigm. To avoid long talk, I would submit a PR before COB Friday and we can see how it goes. 
No fears guys. We would learn together by challenging ourselves. No less I guess but more I assume.

**Comment by akinjide** [comment]
You should remember that the FB community will be using this project as a means to learn React, if we spin up boilerplates, I don't think that will help the FB community learn react.

**Comment by rowlandekemezie** [comment]
No qualms then. You can merge the branch that @andela-eakinyele worked on and we can take it from there. 

I'm closing this issue.
